Repository processing/p5.js-web-editor, pull requests merged in 2023-11, with the labels that each got.

#2398 docs: add default stories for IDE components
  client/modules/IDE/components/About.stories.jsx
  client/modules/IDE/components/AssetPreview.stories.jsx
  client/modules/IDE/components/AssetSize.stories.jsx
  client/modules/IDE/components/Console.stories.jsx
  client/modules/IDE/components/ConsoleInput.stories.jsx
  client/modules/IDE/components/CopyableInput.stories.jsx
  client/modules/IDE/components/EditableInput.stories.jsx
  client/modules/IDE/components/Feedback.stories.jsx
  client/modules/IDE/components/FileUploader.stories.jsx
  client/modules/IDE/components/FloatingActionButton.stories.jsx
  client/modules/IDE/components/KeyboardShortcutModal.stories.jsx
  client/modules/IDE/components/NewFileForm.stories.jsx
  client/modules/IDE/components/NewFileModal.stories.jsx
  client/modules/IDE/components/NewFolderForm.stories.jsx
  client/modules/IDE/components/NewFolderModal.stories.jsx
  client/modules/IDE/components/ShareModal.stories.jsx
  client/modules/IDE/components/SketchList.stories.jsx
  client/modules/IDE/components/UploadFileModal.stories.jsx
Labels: documentation

#2400 Account Settings Page UI for mobile devices
  client/styles/components/_account.scss
  client/styles/components/_form-container.scss
  client/styles/components/_forms.scss
Labels: Mobile

#2428 fix: Moda content overflow and Preferences height
  client/styles/components/_modal.scss
  client/styles/components/_preferences.scss
Labels: Mobile

#2456 Test for EditorAccessibility
  client/modules/IDE/components/Editor/index.jsx
  client/modules/IDE/components/EditorAccessibility.jsx
  client/modules/IDE/components/EditorAccessibility.unit.test.jsx
  translations/locales/de/translations.json
  translations/locales/en-US/translations.json
  translations/locales/es-419/translations.json
  translations/locales/fr-CA/translations.json
  translations/locales/hi/translations.json
  translations/locales/it/translations.json
  translations/locales/ja/translations.json
  translations/locales/ko/translations.json
  translations/locales/pt-BR/translations.json
  translations/locales/sv/translations.json
  translations/locales/tr/translations.json
  translations/locales/uk-UA/translations.json
  translations/locales/zh-TW/translations.json
Labels: area:accessibility, testing

#2597 Fix #2499 - typo in error "please enter a email"
  client/modules/User/components/AccountForm.jsx
  client/modules/User/components/SignupForm.jsx
Labels: i18n

#2594 hindi translation for console fixed
  translations/locales/hi/translations.json
Labels: i18n
