Repository processing/p5.js-web-editor, pull requests merged in 2024-06, with the labels that each got.

#2628 fix autocapitalize in mweb safari
  client/modules/User/components/LoginForm.jsx
  client/modules/User/components/SignupForm.jsx
Labels: Bug, Area: Mobile

#2561 Cleaned the codebase by removing unused files inside client/component…
  client/components/AddRemoveButton.jsx
  client/components/NavBasic.jsx
  client/components/OverlayManager.jsx
  client/constants.js
  client/i18n-test.js
  translations/locales/be/translations.json
  translations/locales/de/translations.json
  translations/locales/en-US/translations.json
  translations/locales/es-419/translations.json
  translations/locales/fr-CA/translations.json
  translations/locales/hi/translations.json
  translations/locales/it/translations.json
  translations/locales/ja/translations.json
  translations/locales/ko/translations.json
  translations/locales/pt-BR/translations.json
  translations/locales/sv/translations.json
  translations/locales/tr/translations.json
  translations/locales/uk-UA/translations.json
  translations/locales/ur/translations.json
  translations/locales/zh-CN/translations.json
  translations/locales/zh-TW/translations.json
Labels: Enhancement, Area: Code Quality

#2723 fix username redirection on mWeb
  client/modules/IDE/components/Header/MobileNav.jsx
Labels: Bug

#2550 implement file type icons
  client/modules/IDE/components/FileNode.jsx
  client/modules/IDE/components/FileTypeIcon.jsx
  package-lock.json
  package.json
Labels: Feature Request, Area: Design

#2438 confusing icons hover issue fix #2255
  client/modules/IDE/components/QuickAddList/Icons.jsx
  client/styles/components/_quick-add.scss
Labels: Area: Design, Enhancement

#2638 fixes wrong position of cursor
  client/modules/IDE/components/EditableInput.jsx
Labels: Bug

#2627 fix mweb share collection dropdown
  client/styles/components/_collection.scss
Labels: Bug, Area: Mobile, Area:CSS

#3000 Language dialog box length fixed.
  client/styles/components/_nav.scss
Labels: Bug, Area:CSS

#2974 Disable resizing the textarea in `CollectionCreate` modal
  client/modules/User/components/CollectionCreate.jsx
  client/styles/components/_collection-create.scss
  client/styles/components/_forms.scss
  client/styles/components/_overlay.scss
Labels: Area:CSS

#3142 Rohanjadhav - fixes #3083
  client/components/PreviewNav.jsx
  client/modules/IDE/components/Header/Nav.jsx
  client/modules/IDE/components/Header/__snapshots__/Nav.unit.test.jsx.snap
Labels: Enhancement

#2883 Feature/enhancement of hoverinig buttons
  client/theme.js
Labels: Area: Design, Area:CSS

#2727 Changed arrow color on ConsoleInput
  client/styles/components/_console-input.scss
Labels: Bug, Area:CSS

#3091 fixes #2221 characters getting deleted between file changes
  client/modules/IDE/components/Editor/index.jsx
Labels: Priority:Medium, Bug

#3113 replaced connect with useSelector hook
  client/modules/IDE/components/AssetSize.jsx
Labels: Type:Task, Enhancement

#2465 Changed Shortcut format for better accessibility
  client/modules/IDE/components/Header/Nav.jsx
  client/modules/IDE/components/Header/__snapshots__/Nav.unit.test.jsx.snap
  client/modules/IDE/components/KeyboardShortcutModal.jsx
  client/utils/metaKey.js
Labels: Area:Accessibility

#3028 Added extension renaming with confirmation
  client/modules/IDE/components/FileNode.jsx
Labels: Area:Accessibility, Enhancement

#2467 Added eye icon
  client/modules/User/components/LoginForm.jsx
  client/modules/User/components/SignupForm.jsx
  client/styles/components/_forms.scss
Labels: Feature Request, Area: Design

#2431 changed the searchbar to functional
  client/modules/IDE/components/Searchbar/Searchbar.jsx
Labels: Area: Code Quality

#2799 Use styled-components in CollectionListRow
  client/modules/IDE/components/CollectionList/CollectionListRow.jsx
  client/theme.js
Labels: Type:Task, Area:CSS

#3013 error added that the new password entered should be different from the current password
  client/utils/reduxFormUtils.js
  translations/locales/be/translations.json
  translations/locales/de/translations.json
  translations/locales/en-US/translations.json
  translations/locales/es-419/translations.json
  translations/locales/fr-CA/translations.json
  translations/locales/hi/translations.json
  translations/locales/it/translations.json
  translations/locales/ja/translations.json
  translations/locales/ko/translations.json
  translations/locales/pt-BR/translations.json
  translations/locales/sv/translations.json
  translations/locales/tr/translations.json
  translations/locales/uk-UA/translations.json
  translations/locales/ur/translations.json
  translations/locales/zh-CN/translations.json
  translations/locales/zh-TW/translations.json
Labels: Feature Request

#3101 Add skip link for better keyboard accessibility Fix-#3084
  client/components/SkipLink.jsx
  client/index.jsx
  client/modules/IDE/components/Header/Toolbar.jsx
  client/styles/components/_skip-link.scss
  client/styles/main.scss
  translations/locales/en-US/translations.json
Labels: Area:Accessibility, Bug

#3119 refactor console reducers and actions using redux toolkit
  client/constants.js
  client/modules/IDE/actions/console.js
  client/modules/IDE/reducers/console.js
  client/store.js
Labels: Type:Task, Enhancement

#2910 Upgrade Storybook
  .storybook/main.js
  client/index.stories.mdx
  package.json
Labels: Area: Dependencies, Area: Documentation

#3164 Added beginClip and ednClip functions in p5FunctionKeywords
  client/utils/p5-hinter.js
  client/utils/p5-keywords.js
Labels: Type:Task, Priority:Medium, Bug
