Repository processing/p5.js-web-editor, pull requests merged in 2024-07, with the labels that each got.

#3149 Fix searchbox fit overlays on mobile
  client/modules/App/components/Overlay.jsx
  client/styles/components/_overlay.scss
Labels: Enhancement, Area: Mobile

#2656 Fixes #2653, No Validation for sketch file rename
  client/modules/IDE/components/SketchList.jsx
  client/styles/components/_sketch-list.scss
Labels: Enhancement

#2988 Fix : [#2986] Add ref callback
  client/modules/IDE/components/CollectionList/CollectionListRow.jsx
Labels: Area:Accessibility, Bug
