Repository processing/p5.js-web-editor, pull requests merged in 2024-08, with the labels that each got.

#2972 Implemented Toast Notifications for Error Handling During User Settings Update
  client/modules/User/actions.js
  translations/locales/en-US/translations.json
  translations/locales/hi/translations.json
Labels: Enhancement

#3120 refactor editorAccessibility reducers and actions using redux toolkit
  client/constants.js
  client/modules/IDE/actions/editorAccessibility.js
  client/modules/IDE/reducers/editorAccessibility.js
Labels: Type:Task, Enhancement

#2980 Use styled-components in Loader
  .eslintrc
  client/index.jsx
  client/modules/App/components/loader.jsx
  client/styles/components/_loader.scss
  client/styles/main.scss
  client/theme.js
Labels: Type:Task, Area:CSS

#2395 Added a keyboard shortcut for adding files
  client/common/useKeyDownHandlers.js
  client/modules/IDE/components/Header/Nav.jsx
  client/modules/IDE/components/Header/__snapshots__/Nav.unit.test.jsx.snap
  client/modules/IDE/components/IDEKeyHandlers.jsx
  client/modules/IDE/components/KeyboardShortcutModal.jsx
  translations/locales/en-US/translations.json
Labels: Feature Request, Enhancement

#2957 Implement Asset Modules in Webpack - Fixes #2023
  webpack/config.dev.js
  webpack/config.prod.js
Labels: Type:Task, Area:Optimization

#3221 fix (some) test suite warnings
  client/modules/IDE/components/EditorAccessibility.unit.test.jsx
  client/modules/IDE/components/ErrorModal.unit.test.jsx
  client/modules/IDE/components/FileNode.unit.test.jsx
  server/controllers/project.controller/__test__/createProject.test.js
  server/controllers/project.controller/createProject.js
Labels: Area: Testing
